const actionTypes = {
	LOAD_COUNTRIES: 'LOAD_COUNTRIES',
	LOAD_COUNTRY: 'LOAD_COUNTRY',
	LOAD_COUNTRY_INFO: 'LOAD_COUNTRY_INFO',
	FILTER_COUNTRIES: 'FILTER_COUNTRIES',
	LOAD_COUNTRY_HISTORY_DATA: 'LOAD_COUNTRY_HISTORY_DATA',
	CLEAR_INFECTED_CASES: 'CLEAR_INFECTED_CASES',
	AUTH_LOGIN: 'AUTH_LOGIN',
	AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
	AUTH_SIGNOUT: 'AUTH_SIGNOUT',
	AUTH_SIGNOUT_ERROR: 'AUTH_SIGNOUT_ERROR'
};

export default actionTypes;
